# Generated by Django 5.1.5 on 2025-02-06 12:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_number', models.CharField(max_length=10, unique=True)),
                ('color_name', models.CharField(max_length=100)),
                ('R', models.IntegerField()),
                ('G', models.IntegerField()),
                ('B', models.IntegerField()),
                ('Hex', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_number', models.CharField(max_length=20)),
                ('client', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_usage', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichments', to='api.project')),
            ],
            options={
                'db_table': 'enrichment_usage',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TcgTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme_key', models.CharField(max_length=10, unique=True)),
                ('theme_name', models.CharField(max_length=100)),
                ('fill', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('fill_color', models.CharField(default='', max_length=10)),
                ('transparency', models.CharField(max_length=10)),
                ('border', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('weight', models.CharField(max_length=10)),
                ('excel_fill', models.CharField(max_length=10)),
                ('excel_text', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('color_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcg_themes', to='api.colorkey')),
            ],
        ),
        migrations.CreateModel(
            name='MarketArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('ma_type', models.CharField(choices=[('radius', 'Radius'), ('zip', 'Zip Code'), ('county', 'County'), ('place', 'Place'), ('tract', 'Census Tract'), ('block', 'Census Block'), ('blockgroup', 'Census Block Group'), ('cbsa', 'CBSA'), ('state', 'State'), ('usa', 'USA')], max_length=20)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('style_settings', models.JSONField(default=dict)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('radius_points', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_areas', to='api.project')),
            ],
            options={
                'ordering': ['order', '-last_modified'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MapConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tab_name', models.CharField(max_length=100)),
                ('visualization_type', models.CharField(blank=True, max_length=50, null=True)),
                ('area_type', models.CharField(choices=[('radius', 'Radius'), ('zip', 'Zip Code'), ('county', 'County'), ('place', 'Place'), ('tract', 'Census Tract'), ('block', 'Census Block'), ('blockgroup', 'Census Block Group'), ('cbsa', 'CBSA'), ('state', 'State'), ('usa', 'USA')], max_length=20)),
                ('layer_configuration', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_configurations', to='api.project')),
            ],
            options={
                'ordering': ['order', '-last_modified'],
                'unique_together': {('project', 'tab_name')},
            },
        ),
        migrations.CreateModel(
            name='StylePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('styles', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_style_presets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_presets', to='api.project')),
            ],
            options={
                'ordering': ['-last_modified'],
                'unique_together': {('name', 'is_global'), ('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VariablePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('variables', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variable_presets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_presets', to='api.project')),
            ],
            options={
                'ordering': ['-last_modified'],
                'unique_together': {('name', 'is_global'), ('project', 'name')},
            },
        ),
    ]
