# Generated by Django 5.1.6 on 2025-04-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketarea',
            name='drive_time_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapconfiguration',
            name='area_type',
            field=models.CharField(choices=[('radius', 'Radius'), ('drivetime', 'Drive Time'), ('zip', 'Zip Code'), ('county', 'County'), ('place', 'Place'), ('tract', 'Census Tract'), ('block', 'Census Block'), ('blockgroup', 'Census Block Group'), ('cbsa', 'CBSA'), ('state', 'State'), ('usa', 'USA'), ('custom', 'Custom Data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketarea',
            name='ma_type',
            field=models.CharField(choices=[('radius', 'Radius'), ('drivetime', 'Drive Time'), ('zip', 'Zip Code'), ('county', 'County'), ('place', 'Place'), ('tract', 'Census Tract'), ('block', 'Census Block'), ('blockgroup', 'Census Block Group'), ('cbsa', 'CBSA'), ('state', 'State'), ('usa', 'USA'), ('custom', 'Custom Data')], max_length=20),
        ),
    ]
