# Generated by Django 5.1.3 on 2024-11-24 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_number", models.CharField(max_length=20, unique=True)),
                ("client", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_modified"],
            },
        ),
        migrations.CreateModel(
            name="MarketArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "ma_type",
                    models.CharField(
                        choices=[
                            ("zip", "Zip Code"),
                            ("county", "County"),
                            ("place", "Place"),
                            ("tract", "Census Tract"),
                            ("block", "Census Block"),
                            ("blockgroup", "Census Block Group"),
                            ("drivetime", "Drive Time"),
                            ("radius", "Radius"),
                            ("cbsa", "CBSA"),
                            ("state", "State"),
                            ("usa", "USA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("geometry", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_areas",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_modified"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
