# Generated by Django 5.1.3 on 2024-11-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_project_marketarea_delete_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketarea",
            name="locations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketarea",
            name="radius_points",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketarea",
            name="style_settings",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="marketarea",
            name="ma_type",
            field=models.CharField(
                choices=[
                    ("radius", "Radius"),
                    ("zip", "Zip Code"),
                    ("county", "County"),
                    ("place", "Place"),
                    ("tract", "Census Tract"),
                    ("block", "Census Block"),
                    ("blockgroup", "Census Block Group"),
                    ("cbsa", "CBSA"),
                    ("state", "State"),
                    ("usa", "USA"),
                ],
                max_length=20,
            ),
        ),
    ]
