# Generated by Django 5.1.6 on 2025-05-08 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_marketarea_drive_time_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketarea',
            name='site_location_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapconfiguration',
            name='area_type',
            field=models.CharField(choices=[('radius', 'Radius'), ('drivetime', 'Drive Time'), ('zip', 'Zip Code'), ('county', 'County'), ('place', 'Place'), ('tract', 'Census Tract'), ('block', 'Census Block'), ('blockgroup', 'Census Block Group'), ('cbsa', 'CBSA'), ('state', 'State'), ('usa', 'USA'), ('custom', 'Custom Data'), ('site_location', 'Site Location')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketarea',
            name='ma_type',
            field=models.CharField(choices=[('radius', 'Radius'), ('drivetime', 'Drive Time'), ('zip', 'Zip Code'), ('county', 'County'), ('place', 'Place'), ('tract', 'Census Tract'), ('block', 'Census Block'), ('blockgroup', 'Census Block Group'), ('cbsa', 'CBSA'), ('state', 'State'), ('usa', 'USA'), ('custom', 'Custom Data'), ('site_location', 'Site Location')], max_length=20),
        ),
        migrations.CreateModel(
            name='LabelPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_id', models.CharField(max_length=255)),
                ('x_offset', models.FloatField()),
                ('y_offset', models.FloatField()),
                ('font_size', models.IntegerField(default=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('visibility', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_labels', to=settings.AUTH_USER_MODEL)),
                ('map_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.mapconfiguration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_positions', to='api.project')),
            ],
            options={
                'ordering': ['-last_modified'],
                'unique_together': {('project', 'label_id')},
            },
        ),
    ]
