# Generated by Django 5.1.6 on 2025-05-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_marketarea_site_location_data_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labelposition',
            unique_together={('project', 'map_configuration', 'label_id')},
        ),
        migrations.AddField(
            model_name='labelposition',
            name='background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labelposition',
            name='font_weight',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='labelposition',
            name='has_background',
            field=models.BooleanField(default=False),
        ),
    ]
