# Generated by Django 4.2.11 on 2024-12-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_marketarea_options_marketarea_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(max_length=20),
        ),
    ]
