# Generated by Django 4.2.11 on 2024-12-20 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_project_project_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_number', models.CharField(max_length=10)),
                ('color_name', models.CharField(max_length=100)),
                ('R', models.CharField(max_length=3)),
                ('G', models.CharField(max_length=3)),
                ('B', models.CharField(max_length=3)),
                ('Hex', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key_number'],
            },
        ),
    ]
