# Generated by Django 4.2.11 on 2024-12-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_colorkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcgTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_key', models.CharField(max_length=10)),
                ('theme_name', models.CharField(max_length=100)),
                ('fill', models.CharField(max_length=3)),
                ('fill_color', models.CharField(blank=True, max_length=10, null=True)),
                ('transparency', models.CharField(blank=True, max_length=10, null=True)),
                ('border', models.CharField(blank=True, max_length=3, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('excel_fill', models.CharField(blank=True, max_length=10, null=True)),
                ('excel_text', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='colorkey',
            options={},
        ),
        migrations.AlterField(
            model_name='colorkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
